apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-values
  namespace: flux-system
data:
  defaults.yaml: |
    server:
      dataStorage:
        enabled: true
        size: "10Gi"
        mountPath: "/vault/data"
        storageClass: "standard"
        accessMode: ReadWriteOnce
