apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: vault-system
spec:
  method: kubernetes
  mount: kubernetes # The path where K8s auth is enabled in Vault
  kubernetes:
    role: vso-role # The role we will create inside Vault
    serviceAccount: dev-vault-secrets-operator # The VSO service account