apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuthGlobal
metadata:
  name: static-auth-global
  namespace: vault-system
spec:
  vaultConnectionRef: vault-connection
  kubernetes:
    mount: kubernetes 
    role: vso-role
    serviceAccount: dev-vault-secrets-operator