apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth # Matching the name the error is looking for
  namespace: web-apps         # Moving it into the app's home
spec:
  method: kubernetes
  mount: kubernetes
  # Point this to the connection in the vault-system namespace
  vaultConnectionRef: vault-system/dev-vault-connection 
  kubernetes:
    role: vso-role
    serviceAccount: dev-vault-secrets-operator # The SA in the 'web-apps' namespace