apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: vault-system
spec:
  # The internal Kubernetes DNS for your Vault service
  address: http://dev-vault.vault-system.svc.cluster.local:8200
  skipTLSVerify: true