apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: dev-
commonLabels:
  env: development
# Generate a new version of the ConfigMap for Dev
configMapGenerator:
  - name: nginx-values
    namespace: flux-system
    behavior: replace # <--- This replaces the base ConfigMap
    files:
      - nginx-values.yaml   # Points to the file we just created above

# You can now REMOVE the patches block for replicaCount 
# since it's handled in the values.yaml file.
