apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-infra-sync
  namespace: flux-system
spec:
  interval: 1h
  path: ./apps/infrastructure/dev # Points to the new folder
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
