# apps/base/helm-repo.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-repo
  namespace: flux-system
spec:
  type: oci
  interval: 1h # How often to check for new chart versions
  url: oci://registry-1.docker.io/bitnamicharts
