apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: nginx-db-secret
  namespace: web-apps
spec:
  vaultAuthRef: static-auth-global
  mount: secret
  type: kv-v2
  path: nginx/database
  refreshAfter: 1h
  destination:
    name: nginx-db-secret # This name is what Nginx will mount
    create: true