apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-server
  namespace: flux-system # The controller lives here
spec:
  releaseName: nginx-server
  targetNamespace: web-apps # The app will be installed here
  interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    # This force-triggers a rollout if the values change
    #force: true
  chart:
    spec:
      chart: nginx
      version: "22.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: nginx-values
      valuesKey: defaults.yaml
    - kind: ConfigMap
      name: nginx-values
      valuesKey: overrides.yaml
      optional: true
